apiVersion: mahjong.io/v1alpha1
kind: Deployment 
metadata:
  name: microservice-all-in-one
  version: 0.2.0
  description: |
    The solution is designated for containerized microservices on AWS EKS, which provides all-in-one 
    experience to simplify complexity and includes demo application to help understanding all 
    capabilities. The solution will provision two seperated environments(stage and production), see 
    following detail:
    
    - Stage 
      1. VPC (priavte, public, isolation subnets, NAT)
      2. EKS with worker nodes (Spot + On-Demand instances)
      3. Istio
      4. Prometheus, Grafana, Jeager Tracing, Kiali
      5. ArgoCD
      6. Sealed-Secret
      7. Demo applications 
      
    - Production
      1. EKS with worker nodes (Spot + On-Demand instances)
      2. ElastiRedis
      3. Elasticsearch
      4. Istio
      5. Prometheus, Grafana, Jeager Tracing, Kiali
      6. FluentBit
      7. Sealed-Secret
      8. Demo applications
  Author: AWS.Builder
  License: Apache 2.0
  Released: 2020-06-30T00:00:00Z
      
spec:
  template:
    tiles:
      # Generating master key
      tileAwsKmsKeyGenerator010:
        tileReference: AWS-KMS-KeyGenerator
        tileVersion: 0.1.0
        inputs:
          - name: symmetricKeyAlias
            inputValue: majhong/symmetric-key_0
          - name: asymmetricKeyAlias
            inputValue: majhong/asymmetric-key_0

      # ESK Cluster for Prod
      tileEksWithSpotProd:
        tileReference: Eks-with-Spot
        tileVersion: 0.5.0
        inputs:
          - name: cidr
            inputValue: 192.0.0.0/16
          - name: clusterName
            inputValue: mahjong-eks-prod
          - name: clusterVersion
            inputValue: 1.17
          - name: keyPair4EC2
            inputValue: <<parameter>> - key pairs for worker nodes
          - name: capacityInstance
            inputValues: 
              - m5.large
              - r5.large
              - c5.large
      # EKS Cluster for Stage
      tileEksWithSpotStage:
        tileReference: Eks-with-Spot
        tileVersion: 0.5.0
        inputs:
          - name: cidr
            inputValue: 192.0.0.0/16
          - name: clusterName
            inputValue: mahjong-eks-stage
          - name: clusterVersion
            inputValue: 1.17
          - name: keyPair4EC2
            inputValue: <<parameter>> - key pairs for worker nodes
          - name: capacityInstance
            inputValues: 
              - m5.large
              - r5.large
              - c5.large
      
      # ElsatiCache Redis for Prod
      tileAWSElastiCacheRedis506Prod:
        tileReference: AWS-ElastiCache-Redis
        tileVersion: 5.0.6
        dependsOn:
          - tileEksWithSpotProd
        inputs:
          - name: vpc
            # tileInstance.tileName.field
            inputValue: $cdk(tileEksWithSpotProd.Network0.baseVpc)     
          - name: subnetIds
            inputValues:
              - $cdk(tileEksWithSpotProd.Network0.privateSubnetId1)
              - $cdk(tileEksWithSpotProd.Network0.privateSubnetId2)
          - name: redisClusterName
            inputValue: mahjong-redis-prod

      # ElasticSearch for Prod
      tileElasticsearchCmdProd:
        tileReference: AWS-ElasticSearch-CMD
        tileVersion: 7.4.0
        dependsOn: 
          - tileEksWithSpotProd
        inputs:
          - name: domainName
            inputValue: mahjong-es-prod       
          - name: aesAccessRoleArn
            inputValue: $(tileEksWithSpotProd.outputs.nodesRoleARN)
      
      # FluentBit for Prod
      tileFluentBit4AesProd:
        tileReference: FluentBit-For-AES
        tileVersion: 1.4.6
        dependsOn: 
          - tileElasticsearchCmdProd
        inputs:
          - name: clusterName
            inputValue: $(tileEksWithSpotProd.outputs.clusterName)       
          - name: masterRoleARN
            inputValue: $(tileEksWithSpotProd.outputs.masterRoleARN)
          - name: aesEndpoint
            inputValue: https://$(tileElasticsearchCmdProd.outputs.domainEndpoint)

      # Istio for Prod
      tileIstio0ForProd:
        tileReference: Istio0
        tileVersion: 1.6.4
        dependsOn: 
          - tileEksWithSpotProd
        inputs:
          - name: clusterName
            inputValue: $(tileEksWithSpotProd.outputs.clusterName)
          - name: masterRoleARN
            inputValue: $(tileEksWithSpotProd.outputs.masterRoleARN)

      # Istio for Stage
      tileIstio0ForStage:
        tileReference: Istio0
        tileVersion: 1.6.4
        dependsOn: 
          - tileEksWithSpotStage
        inputs:
          - name: clusterName
            inputValue: $(tileEksWithSpotStage.outputs.clusterName)
          - name: masterRoleARN
            inputValue: $(tileEksWithSpotStage.outputs.masterRoleARN)

      # Install SealedSecret for Prod
      tileSealedSecret010Prod:
        tileReference: SealedSecret-With-Existing-EKS
        tileVersion: 0.1.0
        dependsOn: 
          - tileEksWithSpotProd
        inputs:
          - name: clusterName
            inputValue: $(tileEksWithSpotProd.outputs.clusterName)
          - name: masterRoleARN
            inputValue: $(tileEksWithSpotProd.outputs.masterRoleARN)

      # Install SealedSecret for Stage
      tileSealedSecret010Stage:
        tileReference: SealedSecret-With-Existing-EKS
        tileVersion: 0.1.0
        dependsOn: 
          - tileEksWithSpotStage
        inputs:
          - name: clusterName
            inputValue: $(tileEksWithSpotStage.outputs.clusterName)
          - name: masterRoleARN
            inputValue: $(tileEksWithSpotStage.outputs.masterRoleARN)

      # ArgoCD
      tileArgocdWithExsitingEks161x:
        tileReference: Argocd-With-Existing-EKS
        tileVersion: 1.6.1x
        # !!! Using first dependent tileInstance to determine rootTileInstance !!!
        dependsOn: 
          - tileIstio0ForStage
          - tileIstio0ForProd
        inputs:
          - name: clusterName
            inputValue: $(tileEksWithSpotStage.outputs.clusterName)         
          - name: masterRoleARN
            inputValue: $(tileEksWithSpotStage.outputs.masterRoleARN) 
          - name: prodClusterCertificateAuthorityData
            inputValue: $(tileEksWithSpotProd.outputs.clusterCertificateAuthorityData)
          - name: prodClusterArn
            inputValue: $(tileEksWithSpotProd.outputs.clusterArn)
          - name: prodClusterEndpoint
            inputValue: $(tileEksWithSpotProd.outputs.clusterEndpoint)
          - name: prodClusterName
            inputValue: $(tileEksWithSpotProd.outputs.clusterName)
          - name: prodMasterRoleARN
            inputValue: $(tileEksWithSpotProd.outputs.masterRoleARN)
          - name: githubUser
            inputValue: <<parameter>> - github user
          - name: githubAccessToken
            inputValue: <<parameter>> - github access token
          - name: appConfRepo
            inputValue: go-microservice-all-in-one-config
          - name: appConfRepoBranch
            inputValue: master
      
      # Inject DEMO Applications & setup CI+CD
      tileGoBumblebeeJazz071x:
        tileReference: Go-Bumblebee-Jazz
        tileVersion: 0.7.1x
        dependsOn: 
          - tileArgocdWithExsitingEks161x
        inputs:
          - name: appConfRepoUser
            inputValue: <<parameter>> - github user
          - name: appConfRepoAccessToken
            inputValue: <<parameter>> - github access token
          - name: appConfRepo
            inputValue: go-microservice-all-in-one-config
          - name: appConfRepoBranch
            inputValue: master
          - name: appRepoUser
            inputValue: mahjong-contributions
          - name: appRepo
            inputValue: go-bumblebee-jazz
          - name: appRepoBranch
            inputValue: master
          - name: kmsKeyID
            inputValue: $(tileAwsKmsKeyGenerator010.outputs.symmetricKeyID)
          - name: argocdBaseUrl
            inputValue: $(tileArgocdWithExsitingEks161x.outputs.argocdBaseUrl)
          - name: argocdUser
            inputValue: $(tileArgocdWithExsitingEks161x.outputs.user)
          - name: argocdPassword
            inputValue: $(tileArgocdWithExsitingEks161x.outputs.password)
          - name: prodClusterEndpoint
            inputValue: $(tileEksWithSpotProd.outputs.clusterEndpoint)
          - name: prodClusterName
            inputValue: $(tileEksWithSpotProd.outputs.clusterName)
          - name: prodMasterRoleARN
            inputValue: $(tileEksWithSpotProd.outputs.masterRoleARN)
          - name: stageClusterName
            inputValue: $(tileEksWithSpotStage.outputs.clusterName)
          - name: stageMasterRoleARN
            inputValue: $(tileEksWithSpotStage.outputs.masterRoleARN)
          - name: prodRedisEndpoint
            inputValue: $(tileAWSElastiCacheRedis506Prod.outputs.redisEndpoint)


  summary:
    description: |
      ++++++++++++++++++++++++++++++++++++++++++++++++++++
      +   Perfect Microservices with Demo Application    +
      ++++++++++++++++++++++++++++++++++++++++++++++++++++
    outputs:
      - name: EKS Cluster for Production
        value: $(tileEksWithSpotProd.outputs.clusterName)
      - name: Master role for Production Cluster
        value: $(tileEksWithSpotProd.outputs.masterRoleARN)
      - name: Endpoint for Production Cluster
        value: $(tileEksWithSpotProd.outputs.clusterEndpoint)
      - name: Update KUBECONFIG for Prodcution
        value: aws eks update-kubeconfig --name $(tileEksWithSpotProd.outputs.clusterName) --region $(tileEksWithSpotProd.outputs.regionOfCluster) --role-arn $(tileEksWithSpotProd.outputs.masterRoleARN)

      - name: EKS Cluster for Stage
        value: $(tileEksWithSpotStage.outputs.clusterName)
      - name: Master role for Staging Cluster
        value: $(tileEksWithSpotStage.outputs.masterRoleARN)
      - name: Endpoint for Staging Cluster
        value: $(tileEksWithSpotStage.outputs.clusterEndpoint)
      - name: Update KUBECONFIG for Prodcution
        value: aws eks update-kubeconfig --name $(tileEksWithSpotStage.outputs.clusterName) --region $(tileEksWithSpotStage.outputs.regionOfCluster) --role-arn $(tileEksWithSpotStage.outputs.masterRoleARN)

      - name: Endpoint for AgroCD
        value: $(tileArgocdWithExsitingEks161x.outputs.argocdBaseUrl)
      - name: Administrator for AgroCD
        value: $(tileArgocdWithExsitingEks161x.outputs.user)
      - name: Password for AgroCD Administrator
        value: $(tileArgocdWithExsitingEks161x.outputs.password)
      - name: Jazz Endpoint for Prod
        value: http://$(tileIstio0ForProd.outputs.ingressHost)
      - name: Jazz Endpoint for Stage
        value: http://$(tileIstio0ForStage.outputs.ingressHost)
      - name: Beijing Air for Stage
        value: http://$(tileIstio0ForStage.outputs.ingressHost)/air/v1/city/beijing
      
    notes:
      - |
        Jaeger tracing : kubectl port-forward svc/tracing 8080:80 -n istio-system
      - |
        Prometheus : kubectl port-forward svc/prometheus 9090:9090 -n istio-system
      - |
        Grafana : kubectl port-forward svc/grafana 3000:3000 -n istio-system
      - |
        Kiali: kubectl port-forward svc/kiali 20001:20001 -n istio-system
      - |
        Locust: kubectl port-forward svc/locust 8089:8089 -n go-bumblebee
