apiVersion: mahjong.io/v1alpha1
kind: Deployment 
metadata:
  name: elasticsearch-simple
  version: 0.1.0
  description: |
    The solution is designated to provision AWS Elasticsearch with ultra warm nodes.
  Author: AWS.Builder
  License: Apache 2.0
  Released: 2020-06-30  

spec:
  template:
    tiles:
      tileAwsElasticSearch740:
        tileReference: AWS-ElasticSearch-CMD
        tileVersion: 7.4.0
        inputs:
          - name: domainName
            inputValue: mahjong-es-simple401        
          

  summary:
      description: AWS ElasticSerach Example 
      outputs:
        - name: Domain Name
          value: $(tileAwsElasticSearch740.outputs.domainName)
        - name: Domain Endpoint
          value: $(tileAwsElasticSearch740.outputs.domainEndpoint)

      notes: []
    