apiVersion: mahjong.io/v1alpha1
kind: Deployment 
metadata:
  name: argocd-with-existing-eks
  version: 0.1.0
  description: |
    The solution is a simple demo to provision continiouse delivery tool - ArgoCD on your 
    choosing EKS.
  Author: AWS.Builder
  License: Apache 2.0
  Released: 2020-06-30T00:00:00Z  

spec:
  template:
    tiles:
      # ArgoCD
      tileArgocdWithExsitingEks152:
        tileReference: Argocd-With-Existing-EKS
        tileVersion: 1.5.6
        inputs:
          - name: clusterName
            inputValue: mahjong-eks-stage         
          - name: masterRoleARN
            inputValue: arn:aws:iam::530820415924:role/EksWithSpotStacktileEksWi-EksWithSpotEksClusterMas-ZGPEKQ6OY9A1 
      

  summary:
    description: |
      ++++++++++++++++++++++++++++++++++++++++++++++++++++
      +   Perfect Microservices with Demo Application    +
      ++++++++++++++++++++++++++++++++++++++++++++++++++++
    outputs:
      - name: Endpoint for AgroCD
        value: $(tileArgocdWithExsitingEks152.outputs.argocdBaseUrl)
      - name: Administrator for AgroCD
        value: $(tileArgocdWithExsitingEks152.outputs.user)
      - name: Password for AgroCD Administrator
        value: $(tileArgocdWithExsitingEks152.outputs.password)
     
    notes: []