apiVersion: mahjong.io/v1alpha1
kind: Deployment 
metadata:
  name: kms-simple
  version: 0.1.0
  description: |
    The solution is a simple demo to generate symmetric and asymmetric on KMS.
  Author: AWS.Builder
  License: Apache 2.0
  Released: 2020-06-30  

spec:
  template:
    tiles:
      # Generating master key
      tileAwsKmsKeyGenerator010:
        tileReference: AWS-KMS-KeyGenerator
        tileVersion: 0.1.0
        inputs:
          - name: symmetricKeyAlias
            inputValue: majhong/symmetric-key_0
          - name: asymmetricKeyAlias
            inputValue: majhong/asymmetric-key_0

  summary:
    description: simple
    outputs: []
    notes: []