apiVersion: mahjong.io/v1alpha1
kind: Deployment 
metadata:
  name: istio-simple
  version: 0.1.0
  description: |
    The solution is a simple demo to provision mesh service framework - Istio on your 
    choosing EKS.
  Author: AWS.Builder
  License: Apache 2.0
  Released: 2020-06-30T00:00:00Z  

spec:
  template:
    tiles:
      # Istio for Stage
      tileIstio0ForProd:
        tileReference: Istio0
        tileVersion: 1.6.4
        inputs:
          - name: clusterName
            inputValue: <Replace clusterName by value>
          - name: masterRoleARN
            inputValue: <Replace masterRoleARN by value>

  summary:
      description: DEMO.
      outputs: 
        - name: installedNamespace
          value: $(tileIstio0ForProd.outputs.installedNamespace)
        - name: ingressHost
          value: $(tileIstio0ForProd.outputs.ingressHost)
        - name: ingressPort
          value: $(tileIstio0ForProd.outputs.ingressPort)
        - name: secureIngressHost
          value: $(tileIstio0ForProd.outputs.secureIngressHost)
        - name: tcpIngressPort
          value: $(tileIstio0ForProd.outputs.tcpIngressPort)
      notes: []